name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
      working-directory: ./rockstarsithelloworld
    - run: npm run build --if-present
      working-directory: ./rockstarsithelloworld
    - run: npm test
      working-directory: ./rockstarsithelloworld